import psycopg

def init_db():
    conn = psycopg.connect("dbname=openglucodb user=opengluco password=sugarbase host=postgres")
    with conn:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS "users" (
                  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  "name" varchar,
                  "surname" varchar,
                  "email" varchar,
                  "password" varchar,
                  "created_at" timestamp
                );

                CREATE TABLE IF NOT EXISTS "connections" (
                  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  "user_id" integer,
                  "username" varchar,
                  "password" varchar,
                  "type" varchar,
                  "account_id" varchar,
                  "region" varchar
                );

                ALTER TABLE "connections" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
            """)
    return conn

def get_conn():
    return psycopg.connect("dbname=openglucodb user=opengluco password=sugarbase host=postgres")